config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  
  get 'welcome/index'
  resources :coins

  get '/inicio', to: 'welcome#index'

  root to: "welcome#index"
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type, optional: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :set_locale

    def set_locale

        if params[:locale]
            cookies[:locale] = params[:locale]
        end

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end

    end

end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  #layout "adm"
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :create, :edit, :update]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy!

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy!

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @nome = params[:nome]

    
    @curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def locale(locale)
        if I18n.locale == :en
            "Estados unidos"
        else
            'Brasil'
        end
    end

    def data_br(data_us)
        data_us.strftime('%d/%m/%Y')
    end

    def nome_aplicacao
        "CRYPTO WALLET APP"
    end

    def ambiente_rails

        if Rails.env.development?
            t('dev')
        elsif Rails.env.production?
            t('prod')
        else
            t('test')
        end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong><%= t('desc') %></strong>
    <%= coin.description %>
  </p>

  <p>
    <strong><%= t('acronym') %>:</strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong><%= t('image') %>:</strong>
    <img src="<%= coin.url_image %>" width="50px"/>
  </p>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>
      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="p-2">
    <div>
      <%= form.label t('desc'), style: "display: block" %>
      <%= form.text_field :description %>
    </div>
    <div>
      <%= form.label t('acronym'), style: "display: block" %>
      <%= form.text_field :acronym %>
    </div>
    <div>
      <%= form.label t('url_image'), style: "display: block" %>
      <%= form.text_field :url_image %>
    </div>
    <div>
      <%= form.label t('mining_type'), style: "display: block" %>
      <%=  form.select('mining_type_id', @mining_type_options , {include_blank: true}) %>
    </div>
    <div>
      <%= form.submit alt="#{t('updatecoin')}", class: 'btn btn-warning mt-2' %>
    </div>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1 class="m-2"><%= t('editing_h1') %></h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('seecoin'), @coin, class: "btn btn-primary" %>
  <%= link_to t('backcoin'), coins_path, class: 'btn btn-info' %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= t('coins') %></h1>
<table class="table table-striped">
  <thead class="">
    <tr>
      <th><%= t('desc') %></th>
      <th><%= t('acronym') %></th>
      <th colspan=2><%= t('image') %></th>
      <th colspan=3></th>
    </tr>
  </thead>
  <tbody class="">
    <% @coins.each do |coin| %>
      <tr class="">
        <td><%= coin.description %> </td>
        <td><%= coin.acronym %> </td>
        <td> <img src="<%= coin.url_image %>" width="40px" height="40px"/> </td>
        <td> <%= link_to t('show'), coin, class: "btn btn-info" %>  </td>
        <td><%= link_to t("edit"), edit_coin_path(coin), class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex gap-2">
  <%= link_to t('newcoin'), new_coin_path, class: "btn btn-success"  %>
  <%= link_to t("welcomepage"), '/', class: 'btn btn-info' %>
</div>

app/views/coins/new.html.erb
<h1><%= "#{t('new')} #{t('coin')}" %></h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="m-2">
  <%= render @coin %>
  <div>
    <%= link_to t('edit'), edit_coin_path(@coin) %> |
    <%= link_to t('back'), coins_path %>
    <%= button_to t('delete'), @coin, method: :delete , class: "btn btn-danger"%>
  </div>
</div>

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWalletRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  

  <body class="w-100 h-100 d-flex flex-column justify-content-center align-items-center">
    administrativo
    
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWalletRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>

  
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>
      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <%= form.label t('desc'), style: "display: block" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label t('acronym'), style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>
  <div class="mt-2">
    <%= form.submit alt="#{t('updatemtype')}",class: 'btn btn-warning'  %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
    <strong>Description:</strong>
    <%= mining_type.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= mining_type.acronym %>
  </p>

</div>

app/views/mining_types/edit.html.erb
<div class="p-2">
  <h1><%= "#{t('edit')} #{t('mining_type')}" %></h1>
  <%= render "form", mining_type: @mining_type %>
  <br>
  <div>
    <%= link_to "#{t('show')} #{t('mining_type').downcase}", @mining_type %> |
    <%= link_to "#{t('back')}", mining_types_path %>
  </div>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>
<h1><%= "#{t('mining_types_page')}" %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('desc') %></th>
      <th><%= t('mining_type') %></th>
      <th colspan=3></th>
    </tr>
  </thead>
  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t("show"), mining_type %></td>
        <td><%= link_to t("edit"), edit_mining_type_path(mining_type) %></td>
        <td><%= button_to t("remove"), mining_type, method: :delete, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="d-flex gap-2">
<%= link_to t('newminingtype'), new_mining_type_path, class: "btn btn-success ms-2" %>
<%= link_to t("welcomepage"), '/', class: 'btn btn-info' %>
</div>

app/views/mining_types/new.html.erb
<h1><%=  "#{t('new')} #{t('mining_type').downgrade}" %></h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to "#{t('edit')}#{t('mining_type')}", edit_mining_type_path(@mining_type) %> |
  <%= link_to "#{t('back')}", mining_types_path %>

  <%= button_to t('remove'), @mining_type, method: :delete %>
  
</div>

app/views/welcome/_menu.html.erb
<div class="d-flex gap-2">
    <%= link_to t('coinregister'), "/coins", class: "btn btn-primary"%>
    <%= link_to t('mining_types'), "mining_types", class: "btn btn-primary" %>
</div>

app/views/welcome/index.html.erb
  
<header class="d-flex w-100  justify-content-end gap-2 align-items-center pe-2" style="height: 30px;">
<p class="m-0 p-0"> <%=  link_to t('port'), '?locale=pt-BR', class: "text-decoration-none" %></p>
<p class="m-0 p-0"> <%=  link_to t('ing'), '?locale=en', class: "text-decoration-none"  %>  </p>
</header>
<div class="bg-secondary m-3 p-3 rounded" style="--bs-bg-opacity: .5;"->
  <h1 class=""><%= t('welcome') %></h1>
  <p><%=  t('presentation') %></p>
  <hr/>
  <p><%= t('welcomeoptions') %></p>
  <%= render "menu" %>
  <p class="mt-2">
    <%= t('youareon') %> <strong class="text-danger"><%= ambiente_rails() %></strong>
  </p>
</div>